using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.Networking;

// NOTE: In order to avoid copyright issues, the music file is not uploaded to the repository.
// To get the sound playing in the online demo generated by the CI/CD, this script downloads the song from the web server.

public class MusicController : MonoBehaviour
{
    private const string ALTERNATIVE_AUDIO_URL = "https://savgs.xoanweb.com/wild-furious/demo/main_menu_song__compressed.ogg";
    private const string ALTERNATIVE_AUDIO_NAME = "main_menu_song__compressed.ogg";

    private static MusicController instance;

    [SerializeField] private AudioSource audioSource = null;

    private void Awake()
    {
        if (instance == null) instance = this;
        else Destroy(gameObject);
    }

    public void Play()
    {
        if (audioSource != null && !audioSource.isPlaying)
        {
            if (audioSource.clip != null)
            {
                audioSource.Play();
            }
            else
            {
                StartCoroutine(GetOnlineAudioClip());
            }
        }

        DontDestroyOnLoad(gameObject);
    }

    public void Stop()
    {
        if (audioSource != null && audioSource.isPlaying) audioSource.Stop();
        Destroy(gameObject);
    }

    private IEnumerator GetOnlineAudioClip()
    {
        UnityWebRequest www = UnityWebRequestMultimedia.GetAudioClip(ALTERNATIVE_AUDIO_URL, AudioType.OGGVORBIS);
        yield return www.SendWebRequest();

        if (www.isNetworkError || www.isHttpError)
        {
            Debug.LogWarning(www.error);
        }
        else
        {
            AudioClip clip = DownloadHandlerAudioClip.GetContent(www);
            clip.name = ALTERNATIVE_AUDIO_NAME;
            audioSource.clip = clip;
            audioSource.Play();
        }
    }
}
