version: '3'
services:
    server:
        build: .
        image: ranking_server
        restart: unless-stopped
        expose:
          - "8080"
        networks:
            - proxy
            - default
        environment:
            VIRTUAL_HOST: "8080"
            VIRTUAL_HOST: "ranking-api.savgs.xoanweb.com"
            LETSENCRYPT_HOST: "ranking-api.savgs.xoanweb.com"
            LETSENCRYPT_EMAIL: "xoancosmed@gmail.com"
        logging:
            driver: "json-file"
            options:
                max-size: "50m"
                max-file: "5"
                compress: "true"

networks:
  proxy:
    external: true